FROM postgis/postgis:latest

RUN apt-get update && \
    apt-get install -y gdal-bin postgresql-client && \
    apt-get clean


COPY init-scripts/load_geojson.sh /docker-entrypoint-initdb.d/load_geojson.sh

VOLUME ["/data/db"]
